### ISSUE TITLE
Entering Dormant (shut-down, deep-sleep ) mode

### ISSUE THREAD

**Issue by MarkoSagadin** [SodaqMoja/Microchip_RN487x#5]
Greetings,

I was testing different power modes of RN4871 Bluetooth module and their current consumption. I found out that after entering dormant mode (as named in this library) was not drawing 1.7 uA as written in datasheet but it was more around 75 uA. 

During my search for the solution on internet I came across this [post](https://www.microchip.com/forums/m1056361.aspx) by user tunelabguy.  He described the solution for really achieving low current consumption: after sending command "O,0\r" over UART, he suggested to wait for 200 ms and then pull RX_IND pin high. RX_IND pin is known as BLUETOOTH_WAKE in your library.

Making a small change in dormantMode() method helped to achieve current consumption of 1.7 uA.  Here is the changed  dormantMode() method:

`bool Rn487xBle::dormantMode(void)`
`{`
 ` debugPrintLn("[dormantMode]") ;`
  
  `sendCommand(SET_DORMANT_MODE) ;`
  `delay(200) ;`
  `digitalWrite(BLUETOOTH_WAKE, HIGH);` 
  `delay(200) ;`
  `digitalWrite(BLUETOOTH_WAKE, LOW);`

  `// module does not send confirmation`
  `return true ;`
`}`

**Comment by GabrielNotman** [comment]
Thanks for this, I have added it to the next release (1.0.3) which will be out soon.
